#!/usr/bin/env bash

##	(c)2019 Colin Vanden Heuvel. All rights reserved.
##	
##	For the exclusive use of the University of Wisconsin - Madison

##
##	DO NOT EDIT THIS FILE UNLESS INSTRUCTED TO DO SO
##


if [ "$1" == "clean" ]; then
	rm -f jacobian_op
	exit 0
fi


module load gcc/recommended
	$CC -O3 -fopenmp -std=c11 -lm -lgomp jacobian_cpu.c -o jacobian_op
module unload gcc/recommended


